In [66]:
import gym

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np

def step(action, num_steps=1):
    for a in range(num_steps):
        env.step(action)

def all_but(inds, arr, rem):
    new_inds
    new_arr = [a for i,a in enumerate(arr) if i not in rem]

Noop = 0
Fire = 1
Right = 2
Left = 3

##### Pick Game

In [4]:
env = gym.make("MontezumaRevenge-v4")
env.reset();

##### On Macs this will open a separate window with the game. Try to get this window split-screened with this notebook.

In [4]:
env.render("human")

##### Repeat the Below Cell To Step Through The Game

In [65]:
r0 = env.env.ale.getRAM()
step(0)  # change this action
env.render("human")
r1 = env.env.ale.getRAM()
diff = r1 - r0
print(np.arange(128)[diff!=0]) # prints rams that change
print(r0[diff!=0])
print(r1[diff!=0])

[  0   5   6  47  53  89  90 102 107 109]
[208  50 174  22  18  77  18 127  24   0]
[212 232  77  23   8   1  19 255  27   2]


#### Alternative Matplotlib Way of Stepping Through

In [64]:
i = 0
env.step(1)

for j in range(25):
    r0 = env.env.ale.getRAM()
    if j <= 4:
        obs,_,_,_ = env.step(3)
    else:
        obs,_,_,_ = env.step(2)
    r1 = env.env.ale.getRAM()
    diff = r1 - r0

    diff = diff[None,:]
    diff = np.repeat(diff,20,axis=0)


    plt.figure(i)
    plt.imshow(obs)

    plt.figure(i+1)
    plt.imshow(diff)
    plt.axis("on")
    plt.title(str(np.arange(128)[diff[0,:]>0]) + " \n" +  str(r1[diff[0,:]>0]) )
    #plt.title("90,99,101 | " + " ".join([str(r1[90]),str(r1[99]),str(r1[101])]))
    #plt.title()

    i += 3